services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - container.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      minio_network:
        ipv4_address: 172.35.1.11
    restart: on-failure

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - container.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      minio_network:
        ipv4_address: 172.35.1.12
    restart: on-failure

networks:
  minio_network:
    external: true
